#!/bin/bash
set -euo pipefail

# Signal handler for graceful shutdown
_term() {
    echo "Received SIGTERM, stopping Namecoin Core gracefully..."
    if [ -n "${NAMECOIN_PID:-}" ]; then
        namecoin-cli -datadir=/root/.namecoin -rpcuser="$RPC_USER" -rpcpassword="$RPC_PASS" stop 2>/dev/null || true
        wait "$NAMECOIN_PID" 2>/dev/null || true
    fi
    exit 0
}

trap _term SIGTERM SIGINT

# Read configuration
CONF_FILE="/root/.namecoin/namecoin.conf"

# Generate namecoin.conf from StartOS config if it doesn't exist or needs updating
if [ -f /root/.namecoin/start9/config.yaml ]; then
    echo "Generating namecoin.conf from StartOS configuration..."

    # Extract config values using yq or parse yaml
    RPC_USER=$(yq e '.rpc.username // "namecoin"' /root/.namecoin/start9/config.yaml 2>/dev/null || echo "namecoin")
    RPC_PASS=$(yq e '.rpc.password // ""' /root/.namecoin/start9/config.yaml 2>/dev/null || echo "")
    PRUNE_MODE=$(yq e '.pruning.mode // "disabled"' /root/.namecoin/start9/config.yaml 2>/dev/null || echo "disabled")
    PRUNE_SIZE=$(yq e '.pruning.size // 550' /root/.namecoin/start9/config.yaml 2>/dev/null || echo "550")
    TXINDEX=$(yq e '.txindex // true' /root/.namecoin/start9/config.yaml 2>/dev/null || echo "true")
    DBCACHE=$(yq e '.advanced.dbcache // 450' /root/.namecoin/start9/config.yaml 2>/dev/null || echo "450")
    MAXCONNECTIONS=$(yq e '.advanced.maxconnections // 125' /root/.namecoin/start9/config.yaml 2>/dev/null || echo "125")

    # Generate RPC password if empty
    if [ -z "$RPC_PASS" ]; then
        RPC_PASS=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)
    fi

    cat > "$CONF_FILE" <<EOF
# Namecoin Core configuration - generated by StartOS
# Do not edit manually; changes will be overwritten

# Network
server=1
listen=1
bind=0.0.0.0
port=8334

# RPC
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASS}
rpcbind=0.0.0.0
rpcport=8336
rpcallowip=0.0.0.0/0

# Data
datadir=/root/.namecoin
EOF

    # Pruning
    if [ "$PRUNE_MODE" = "automatic" ]; then
        echo "prune=${PRUNE_SIZE}" >> "$CONF_FILE"
    else
        echo "prune=0" >> "$CONF_FILE"
    fi

    # Transaction index (only if not pruning)
    if [ "$PRUNE_MODE" != "automatic" ] && [ "$TXINDEX" = "true" ]; then
        echo "txindex=1" >> "$CONF_FILE"
    fi

    # Advanced settings
    echo "dbcache=${DBCACHE}" >> "$CONF_FILE"
    echo "maxconnections=${MAXCONNECTIONS}" >> "$CONF_FILE"

    # Namecoin-specific settings
    cat >> "$CONF_FILE" <<EOF

# Namecoin-specific
namehistory=1

# Logging
printtoconsole=1
EOF

else
    # Fallback: create a minimal config
    if [ ! -f "$CONF_FILE" ]; then
        RPC_USER="namecoin"
        RPC_PASS=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)
        cat > "$CONF_FILE" <<EOF
server=1
listen=1
bind=0.0.0.0
port=8334
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASS}
rpcbind=0.0.0.0
rpcport=8336
rpcallowip=0.0.0.0/0
datadir=/root/.namecoin
namehistory=1
printtoconsole=1
EOF
    fi
    RPC_USER=$(grep '^rpcuser=' "$CONF_FILE" | cut -d'=' -f2)
    RPC_PASS=$(grep '^rpcpassword=' "$CONF_FILE" | cut -d'=' -f2)
fi

export RPC_USER
export RPC_PASS

# Check for reindex flag
EXTRA_ARGS=""
if [ -f /root/.namecoin/.reindex ]; then
    EXTRA_ARGS="-reindex"
    rm -f /root/.namecoin/.reindex
    echo "Reindex flag detected. Starting with -reindex..."
fi

echo "Starting Namecoin Core..."
namecoind -datadir=/root/.namecoin -conf="$CONF_FILE" $EXTRA_ARGS &
NAMECOIN_PID=$!

# Wait for the process
wait "$NAMECOIN_PID"
